export const Permission = {
  STUDENTS_READ: 'students:read',
  STUDENTS_WRITE: 'students:write',
  STUDENTS_DELETE: 'students:delete',
  CONTRACTS_READ: 'contracts:read',
  CONTRACTS_WRITE: 'contracts:write',
  CONTRACTS_DELETE: 'contracts:delete',
  TEACHERS_READ: 'teachers:read',
  TEACHERS_WRITE: 'teachers:write',
  TEACHERS_DELETE: 'teachers:delete',
  TEACHERS_VIEW_RATE: 'teachers:view_rate',
  CLASSES_READ: 'classes:read',
  CLASSES_WRITE: 'classes:write',
  CLASSES_DELETE: 'classes:delete',
  CLASSES_LIST: 'classes:list',
  PLANS_READ: 'plans:read',
  PLANS_WRITE: 'plans:write',
  PLANS_DELETE: 'plans:delete',
  LEVELING_READ: 'leveling:read',
  LEVELING_WRITE: 'leveling:write',
  LEVELING_DELETE: 'leveling:delete',
  NPS_READ: 'nps:read',
  NPS_WRITE: 'nps:write',
  NPS_DELETE: 'nps:delete',
  ENROLLMENT_WRITE: 'enrollment:write',
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  USERS_DELETE: 'users:delete',
  SETTINGS_READ: 'settings:read',
  SETTINGS_WRITE: 'settings:write',
  SETTINGS_LIST: 'settings:list',
  DASHBOARD_READ: 'dashboard:read',
  HOUR_CLOSINGS_READ: 'hour_closings:read',
  HOUR_CLOSINGS_WRITE: 'hour_closings:write',
  HOUR_CLOSINGS_APPROVE: 'hour_closings:approve',
  PAYMENTS_READ: 'payments:read',
  PAYMENTS_WRITE: 'payments:write',
} as const

export type PermissionKey = typeof Permission[keyof typeof Permission]
